"""Text cleaning utilities for job descriptions (Phase 5 / Section 18)."""
import re
import html
import unicodedata
from typing import List

# Key phrases found in recruitment boilerplates to filter out entirely
BOILERPLATE_INDICATORS = [
    "equal opportunity employer",
    "affirmative action",
    "qualified applicants will receive consideration",
    "discrimination on the basis of",
    "do not discriminate on the basis",
    "notice to third-party",
    "notice to third party",
    "notice to recruitment agencies",
    "salary range disclaimer",
    "eeo statement",
    "equal employment opportunity",
    "we are an equal opportunity",
    "we are proud to be an equal opportunity",
]

def normalize_unicode(text: str) -> str:
    """Normalize unicode characters (NFKD), typographic quotes, dashes, and bullet points."""
    if not text:
        return ""
    # Normalize unicode characters
    normalized = unicodedata.normalize("NFKD", text)

    # Replace typographic/curly punctuation
    replacements = {
        "\u2018": "'",   # left single quote
        "\u2019": "'",   # right single quote
        "\u201c": '"',   # left double quote
        "\u201d": '"',   # right double quote
        "\u2013": "-",   # en dash
        "\u2014": "-",   # em dash
        "\u2212": "-",   # minus sign
        "\u00a0": " ",   # non-breaking space
        "\u2022": "• ",  # bullet point
        "\u2023": "• ",  # triangular bullet
        "\u25b6": "• ",  # black right-pointing triangle
        "\u25aa": "• ",  # black small square
        "\ufeff": "",    # BOM
    }
    for orig, repl in replacements.items():
        normalized = normalized.replace(orig, repl)

    return normalized

def clean_html(raw_html: str) -> str:
    """Strip HTML tags while preserving line breaks, unescape HTML entities, and remove scripts/styles."""
    if not raw_html:
        return ""

    text = raw_html

    # Strip script and style blocks entirely
    text = re.sub(r"(?is)<script[^>]*>.*?</script>", " ", text)
    text = re.sub(r"(?is)<style[^>]*>.*?</style>", " ", text)

    # Convert structural HTML tags to logical line breaks
    text = re.sub(r"(?i)<br\s*/?>", "\n", text)
    text = re.sub(r"(?i)</(?:p|div|h[1-6]|tr)>", "\n\n", text)
    text = re.sub(r"(?i)<li[^>]*>", "\n• ", text)
    text = re.sub(r"(?i)</li>", "\n", text)

    # Remove all remaining HTML tags
    text = re.sub(r"<[^>]+>", " ", text)

    # Unescape HTML entities (e.g., &amp; -> &, &nbsp; -> ' ', &gt; -> >)
    text = html.unescape(text)

    # Fix space before punctuation caused by stripped inline tags (e.g. "FastAPI ." -> "FastAPI.")
    text = re.sub(r"[ \t]+([,.:;?!])", r"\1", text)

    return text

def remove_duplicates(text: str) -> str:
    """Remove duplicate consecutive lines or identical paragraphs often generated by scrapers."""
    if not text:
        return ""

    lines = text.splitlines()
    cleaned_lines: List[str] = []
    seen_lines = set()

    for line in lines:
        stripped = line.strip()
        if not stripped:
            if cleaned_lines and cleaned_lines[-1] != "":
                cleaned_lines.append("")
            continue

        norm_key = stripped.lower()
        if len(stripped) > 20 and norm_key in seen_lines:
            continue

        seen_lines.add(norm_key)
        cleaned_lines.append(stripped)

    return "\n".join(cleaned_lines)

def remove_boilerplate(text: str) -> str:
    """Filter out non-informative recruitment boilerplate (EEO, recruitment agency warnings)."""
    if not text:
        return ""

    lines = text.splitlines()
    filtered_lines: List[str] = []

    for line in lines:
        lower_line = line.lower()
        # If line contains boilerplate indicators, drop the line
        if any(indicator in lower_line for indicator in BOILERPLATE_INDICATORS):
            continue
        filtered_lines.append(line)

    return "\n".join(filtered_lines)

def normalize_whitespace(text: str) -> str:
    """Collapse excess newlines and horizontal whitespace into readable text formatting."""
    if not text:
        return ""

    # Replace tabs and multiple spaces with a single space per line
    lines = [re.sub(r"[ \t]+", " ", line).strip() for line in text.splitlines()]
    rejoined = "\n".join(lines)

    # Collapse 3 or more consecutive newlines into 2
    rejoined = re.sub(r"\n{3,}", "\n\n", rejoined)

    return rejoined.strip()

def clean_job_text(raw_text: str) -> str:
    """Full Phase 5 cleaning pipeline:
    1. Unicode normalization (NFKD, typographic quotes, symbols)
    2. HTML tag stripping & entity unescaping with paragraph retention
    3. Removal of duplicate lines / paragraphs
    4. Removal of standard recruitment boilerplate
    5. Whitespace and newline normalization
    """
    if not raw_text:
        return ""

    text = normalize_unicode(raw_text)
    text = clean_html(text)
    text = remove_duplicates(text)
    text = remove_boilerplate(text)
    text = normalize_whitespace(text)
    return text
