import React, { useMemo } from 'react';
import {
  Compass,
  Sparkles,
  Clock,
  Briefcase,
  CheckCircle2,
  FolderGit2,
  ArrowRight,
  ShieldCheck,
  RefreshCw,
  AlertCircle,
  History,
} from 'lucide-react';
import { Link } from 'react-router-dom';
import { useRoadmap } from '../hooks/useRoadmap';
import { useCareers } from '../hooks/useCareers';
import type { RoadmapPhase, RoadmapItem, RoadmapProjectItem } from '../types/roadmap';

export const RoadmapPage: React.FC = () => {
  const { careers } = useCareers();
  const {
    careerRoleId,
    setCareerRoleId,
    availableTime,
    setAvailableTime,
    activeRoadmap,
    history,
    loading,
    generating,
    error,
    generate,
    selectRoadmap,
  } = useRoadmap(1);

  const selectedCareer = useMemo(() => {
    return careers.find((c) => c.id === careerRoleId);
  }, [careers, careerRoleId]);

  // Aggregate stats
  const totalItems = useMemo(() => {
    if (!activeRoadmap) return 0;
    return activeRoadmap.phases.reduce((acc, p) => acc + (p.items?.length || 0), 0);
  }, [activeRoadmap]);

  const totalHours = useMemo(() => {
    if (!activeRoadmap) return 0;
    return activeRoadmap.phases.reduce((acc, p) => {
      const phaseHours = p.items?.reduce((itemAcc, i) => itemAcc + (i.estimated_hours || 0), 0) || 0;
      return acc + phaseHours;
    }, 0);
  }, [activeRoadmap]);

  const totalProjects = useMemo(() => {
    if (!activeRoadmap) return 0;
    return activeRoadmap.projects?.length || 0;
  }, [activeRoadmap]);

  return (
    <div className="py-8 max-w-7xl mx-auto space-y-8 animate-fade-in">
      {/* Header & Controls */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6 pb-6 border-b border-slate-800/80">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 text-xs font-semibold mb-3">
            <Compass className="w-3.5 h-3.5" />
            <span>Phase 11 — Personalized Learning Roadmap & Phase Timeline</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
            Personalized Career Roadmap
          </h1>
          <p className="text-slate-400 text-sm mt-1.5 max-w-2xl">
            Empirically grounded curriculum generated by Gemini LLM. Strictly tailored to bridge your
            specific skill gaps without invented statistics.
          </p>
        </div>

        {/* Generate Button */}
        <div className="flex flex-wrap items-center gap-3">
          <button
            onClick={() => generate()}
            disabled={generating || !careerRoleId}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl font-semibold text-sm bg-gradient-to-r from-cyan-500 via-blue-600 to-indigo-600 hover:from-cyan-400 hover:to-indigo-500 text-white shadow-lg shadow-cyan-500/20 transition-all cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {generating ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin text-cyan-200" />
                <span>Synthesizing Curriculum...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4 text-cyan-200" />
                <span>Generate Tailored Roadmap</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Error Banner */}
      {error && (
        <div className="p-4 rounded-xl border border-rose-500/30 bg-rose-500/10 text-rose-300 text-xs flex items-center justify-between">
          <div className="flex items-center gap-2">
            <AlertCircle className="w-4 h-4 text-rose-400 shrink-0" />
            <span>{error}</span>
          </div>
          <button
            onClick={() => generate()}
            className="px-2.5 py-1 rounded bg-rose-500/20 hover:bg-rose-500/30 text-rose-200 font-semibold cursor-pointer"
          >
            Retry
          </button>
        </div>
      )}

      {/* Target Role & Configuration Bar */}
      <div className="p-4 sm:p-5 rounded-2xl border border-slate-800/80 bg-slate-900/50 backdrop-blur-xl shadow-xl flex flex-wrap items-center gap-4">
        {/* Career Role */}
        <div className="flex-1 min-w-[240px]">
          <label className="block text-xs font-medium text-slate-400 mb-1.5 flex items-center gap-1.5">
            <Briefcase className="w-3.5 h-3.5 text-cyan-400" />
            Target Career Role
          </label>
          <select
            value={careerRoleId || ''}
            onChange={(e) => setCareerRoleId(Number(e.target.value))}
            className="w-full bg-slate-950 border border-slate-800 text-white rounded-xl px-3.5 py-2 text-sm focus:outline-none focus:border-cyan-500 cursor-pointer"
          >
            {careers.map((career) => (
              <option key={career.id} value={career.id}>
                {career.name} ({career.category})
              </option>
            ))}
          </select>
        </div>

        {/* Time Commitment */}
        <div className="w-56">
          <label className="block text-xs font-medium text-slate-400 mb-1.5 flex items-center gap-1.5">
            <Clock className="w-3.5 h-3.5 text-cyan-400" />
            Time Commitment
          </label>
          <select
            value={availableTime}
            onChange={(e) => setAvailableTime(e.target.value)}
            className="w-full bg-slate-950 border border-slate-800 text-white rounded-xl px-3.5 py-2 text-sm focus:outline-none focus:border-cyan-500 cursor-pointer"
          >
            <option value="5-10 hours/week">5-10 hours/week (Light)</option>
            <option value="10-15 hours/week">10-15 hours/week (Standard)</option>
            <option value="20+ hours/week">20+ hours/week (Intensive)</option>
          </select>
        </div>

        {/* Saved Roadmaps Dropdown */}
        {history.length > 0 && (
          <div className="w-56">
            <label className="block text-xs font-medium text-slate-400 mb-1.5 flex items-center gap-1.5">
              <History className="w-3.5 h-3.5 text-cyan-400" />
              History ({history.length})
            </label>
            <select
              value={activeRoadmap?.id || ''}
              onChange={(e) => selectRoadmap(Number(e.target.value))}
              className="w-full bg-slate-950 border border-slate-800 text-white rounded-xl px-3.5 py-2 text-sm focus:outline-none focus:border-cyan-500 cursor-pointer"
            >
              {history.map((r) => (
                <option key={r.id} value={r.id}>
                  #{r.id} — {r.career_role_name || 'Roadmap'} (
                  {r.created_at ? new Date(r.created_at).toLocaleDateString() : 'Recent'})
                </option>
              ))}
            </select>
          </div>
        )}
      </div>

      {/* Main Roadmap Display */}
      {generating ? (
        <div className="p-16 rounded-2xl border border-cyan-500/20 bg-slate-900/40 backdrop-blur-xl text-center space-y-4">
          <div className="relative w-16 h-16 mx-auto">
            <div className="absolute inset-0 rounded-full bg-cyan-500/20 animate-ping" />
            <div className="relative w-16 h-16 rounded-full bg-gradient-to-tr from-cyan-500 to-blue-600 flex items-center justify-center text-white shadow-xl shadow-cyan-500/20">
              <Sparkles className="w-8 h-8 animate-spin" />
            </div>
          </div>
          <div>
            <h3 className="text-xl font-bold text-white">Synthesizing Personalized Roadmap</h3>
            <p className="text-xs text-slate-400 max-w-md mx-auto mt-1">
              Analyzing verified market demand, mapping Phase 10 skill gaps, and generating structured
              progressive learning milestones with portfolio projects...
            </p>
          </div>
        </div>
      ) : loading ? (
        <div className="py-20 flex flex-col items-center justify-center gap-3 text-slate-400">
          <RefreshCw className="w-8 h-8 animate-spin text-cyan-400" />
          <span className="text-sm font-medium">Loading roadmap...</span>
        </div>
      ) : !activeRoadmap ? (
        <div className="p-16 rounded-2xl border border-slate-800 bg-slate-900/40 backdrop-blur-xl text-center space-y-4">
          <div className="w-16 h-16 rounded-2xl bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 flex items-center justify-center mx-auto shadow-xl">
            <Compass className="w-8 h-8" />
          </div>
          <div>
            <h3 className="text-xl font-bold text-white">No Active Roadmap Generated</h3>
            <p className="text-xs text-slate-400 max-w-md mx-auto mt-1">
              Click &quot;Generate Tailored Roadmap&quot; above to synthesize an evidence-grounded
              phase-by-phase learning plan for{' '}
              <span className="text-cyan-400 font-semibold">{selectedCareer?.name || 'your target role'}</span>.
            </p>
          </div>
          <button
            onClick={() => generate()}
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 text-white text-xs font-bold hover:from-cyan-400 hover:to-blue-500 shadow-lg shadow-cyan-500/20 transition-all cursor-pointer"
          >
            <Sparkles className="w-4 h-4" />
            <span>Generate First Roadmap</span>
          </button>
        </div>
      ) : (
        <div className="space-y-8">
          {/* Executive Summary Card */}
          <div className="rounded-2xl border border-cyan-500/20 bg-gradient-to-r from-slate-900/95 via-slate-900/70 to-cyan-950/20 p-6 sm:p-8 backdrop-blur-xl shadow-2xl relative overflow-hidden">
            <div className="absolute top-0 right-0 w-96 h-96 bg-cyan-500/5 rounded-full blur-3xl -z-10 pointer-events-none" />

            <div className="flex flex-col md:flex-row md:items-start justify-between gap-4 pb-6 border-b border-slate-800">
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <span className="px-2.5 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 text-xs font-semibold">
                    {activeRoadmap.career_role_name || selectedCareer?.name || 'Target Role'}
                  </span>
                  <span className="px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 text-[10px] font-mono">
                    Verified Grounded
                  </span>
                </div>
                <h2 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
                  {activeRoadmap.title}
                </h2>
                <p className="text-xs sm:text-sm text-slate-300 mt-2 max-w-3xl leading-relaxed">
                  {activeRoadmap.summary}
                </p>
              </div>

              {/* Quick Jump to Gap Page */}
              <Link
                to="/gaps"
                className="shrink-0 inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-slate-700 bg-slate-800/60 hover:bg-slate-800 text-slate-300 hover:text-white text-xs font-medium transition-all"
              >
                <span>View Underpinning Gaps</span>
                <ArrowRight className="w-3.5 h-3.5 text-cyan-400" />
              </Link>
            </div>

            {/* Metrics Bar */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-6 text-xs">
              <div className="p-3 rounded-xl bg-slate-950/50 border border-slate-800">
                <span className="text-slate-400 text-[11px] uppercase tracking-wider block mb-1">
                  Progressive Phases
                </span>
                <div className="text-xl font-bold font-mono text-white">
                  {activeRoadmap.phases?.length || 0} Phases
                </div>
                <span className="text-[10px] text-slate-400">Section 43 Timeline</span>
              </div>

              <div className="p-3 rounded-xl bg-slate-950/50 border border-slate-800">
                <span className="text-slate-400 text-[11px] uppercase tracking-wider block mb-1">
                  Total Milestones
                </span>
                <div className="text-xl font-bold font-mono text-cyan-400">
                  {totalItems} Milestones
                </div>
                <span className="text-[10px] text-slate-400">Skill-linked items</span>
              </div>

              <div className="p-3 rounded-xl bg-slate-950/50 border border-slate-800">
                <span className="text-slate-400 text-[11px] uppercase tracking-wider block mb-1">
                  Estimated Effort
                </span>
                <div className="text-xl font-bold font-mono text-white">
                  ~{totalHours} Hours
                </div>
                <span className="text-[10px] text-slate-400">At {availableTime}</span>
              </div>

              <div className="p-3 rounded-xl bg-slate-950/50 border border-slate-800">
                <span className="text-slate-400 text-[11px] uppercase tracking-wider block mb-1">
                  Portfolio Projects
                </span>
                <div className="text-xl font-bold font-mono text-purple-400">
                  {totalProjects} Projects
                </div>
                <span className="text-[10px] text-slate-400">Section 45 Capstones</span>
              </div>
            </div>
          </div>

          {/* Phase Timeline (Section 43) */}
          <div className="space-y-8 relative">
            {activeRoadmap.phases?.map((phase, pIdx) => (
              <PhaseTimelineCard
                key={phase.id || pIdx}
                phase={phase}
                phaseIndex={pIdx}
                isLast={pIdx === (activeRoadmap.phases?.length || 1) - 1}
              />
            ))}
          </div>

          {/* Section 48 Transparency Guarantee */}
          <div className="p-4 rounded-xl border border-slate-800 bg-slate-900/30 flex items-center justify-between text-xs text-slate-400">
            <div className="flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-cyan-400" />
              <span>
                Section 48 Rigor: Gemini LLM generated strictly using Phase 8/10 deterministic statistics.
                Zero invented market numbers.
              </span>
            </div>
            <span className="font-mono text-[11px] text-slate-500">
              Roadmap ID #{activeRoadmap.id}
            </span>
          </div>
        </div>
      )}
    </div>
  );
};

interface PhaseTimelineCardProps {
  phase: RoadmapPhase;
  phaseIndex: number;
  isLast: boolean;
}

const PhaseTimelineCard: React.FC<PhaseTimelineCardProps> = ({
  phase,
  phaseIndex,
  isLast,
}) => {
  return (
    <div className="relative pl-6 sm:pl-10">
      {/* Vertical Timeline Guide Line */}
      {!isLast && (
        <div className="absolute left-2.5 sm:left-4 top-8 bottom-0 w-0.5 bg-gradient-to-b from-cyan-500 to-slate-800 -z-10" />
      )}

      {/* Timeline Node Bullet */}
      <div className="absolute left-0 top-1.5 w-6 h-6 sm:w-8 sm:h-8 rounded-full bg-slate-950 border-2 border-cyan-400 flex items-center justify-center text-[11px] sm:text-xs font-extrabold font-mono text-cyan-400 shadow-md shadow-cyan-500/20">
        0{phase.phase_number || phaseIndex + 1}
      </div>

      {/* Phase Container */}
      <div className="rounded-2xl border border-slate-800/80 bg-slate-900/40 p-6 sm:p-8 backdrop-blur-xl shadow-xl space-y-6">
        {/* Phase Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-slate-800/80">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xs font-mono font-bold text-cyan-400 uppercase tracking-wider">
                Phase {phase.phase_number || phaseIndex + 1}
              </span>
              <span className="text-slate-600">•</span>
              <span className="text-xs text-slate-400">{phase.items?.length || 0} Milestones</span>
            </div>
            <h3 className="text-xl font-bold text-white tracking-tight">{phase.title}</h3>
          </div>

          {phase.estimated_duration && (
            <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 text-xs font-mono font-semibold self-start sm:self-auto">
              <Clock className="w-3.5 h-3.5" />
              <span>{phase.estimated_duration}</span>
            </div>
          )}
        </div>

        {/* Milestone Items List */}
        <div className="space-y-4">
          {phase.items?.map((item, iIdx) => (
            <RoadmapItemCard key={item.id || iIdx} item={item} />
          ))}
        </div>

        {/* Phase Projects (Section 45 Hands-On Projects) */}
        {phase.projects && phase.projects.length > 0 && (
          <div className="pt-2">
            {phase.projects.map((proj, pIdx) => (
              <PhaseProjectCard key={proj.id || pIdx} project={proj} />
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

interface RoadmapItemCardProps {
  item: RoadmapItem;
}

const RoadmapItemCard: React.FC<RoadmapItemCardProps> = ({ item }) => {
  return (
    <div className="rounded-xl border border-slate-800/80 bg-slate-950/60 p-4 hover:border-slate-700/80 transition-all space-y-2">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
        <div className="flex items-center gap-2.5">
          <div className="p-1 rounded bg-cyan-500/10 text-cyan-400">
            <CheckCircle2 className="w-3.5 h-3.5" />
          </div>
          <span className="font-bold text-white text-sm">{item.title}</span>
          {item.skill_name && (
            <span className="px-2 py-0.5 rounded text-[10px] font-semibold bg-slate-800 text-cyan-300 border border-slate-700">
              {item.skill_name}
            </span>
          )}
        </div>

        {item.estimated_hours > 0 && (
          <span className="text-[11px] font-mono text-slate-400 shrink-0 self-start sm:self-auto">
            ~{item.estimated_hours} Hours
          </span>
        )}
      </div>

      {item.description && (
        <p className="text-xs text-slate-300 leading-relaxed pl-6">{item.description}</p>
      )}

      {item.importance_reason && (
        <div className="ml-6 p-2 rounded-lg bg-slate-900/80 border border-slate-800 text-[11px] text-cyan-300/90 flex items-start gap-1.5">
          <Sparkles className="w-3 h-3 text-cyan-400 shrink-0 mt-0.5" />
          <span>
            <strong className="text-white">Why This Matters:</strong> {item.importance_reason}
          </span>
        </div>
      )}
    </div>
  );
};

interface PhaseProjectCardProps {
  project: RoadmapProjectItem;
}

const PhaseProjectCard: React.FC<PhaseProjectCardProps> = ({ project }) => {
  const diffColors = {
    beginner: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    intermediate: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    advanced: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
  }[project.difficulty || 'intermediate'];

  return (
    <div className="rounded-xl border border-purple-500/30 bg-gradient-to-r from-purple-950/20 via-slate-950/60 to-slate-950/80 p-5 backdrop-blur-xl shadow-lg space-y-3">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <div className="p-1.5 rounded-lg bg-purple-500/20 text-purple-300 border border-purple-500/30">
            <FolderGit2 className="w-4 h-4" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-[10px] font-bold uppercase tracking-wider text-purple-400">
                Phase Capstone Portfolio Project
              </span>
              <span className={`px-2 py-0.5 rounded text-[10px] font-semibold border capitalize ${diffColors}`}>
                {project.difficulty}
              </span>
            </div>
            <h4 className="font-bold text-white text-base mt-0.5">{project.title}</h4>
          </div>
        </div>
      </div>

      <p className="text-xs text-slate-300 leading-relaxed">{project.description}</p>
    </div>
  );
};
